---
env: "local" # local, dev, prod
db_path: "user=postgres password=postgres dbname=postgres sslmode=disable"
storage_path: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
listener:
  addr: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s